---

- name: Configure kubelet.
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet owner=root group=root mode=0644

- name: Enable and ensure all k8s minion services are enabled and started in order.
  service: name={{item}} enabled=true state=started
  with_items:
    - kube-proxy
    - docker
    - kubelet
